#!/usr/bin/env python
# -*- coding: utf-8 -*- #

#AUTHOR = u"Default Author"
#DATE_FORMATS
USE_FOLDER_AS_CATEGORY = False
DEFAULT_CATEGORY = u"General"
DEFAULT_DATE_FORMAT = u"%A, %d de %B de %Y"
DISPLAY_PAGES_ON_MENU = True
DEFAULT_DATE = 'fs'
#DEFAULT_METADATA
#FILENAME_METADATA
DELETE_OUTPUT_DIRECTORY = False
FILES_TO_COPY = (( 'CNAME', 'CNAME'),)
#JINJA_EXTENSIONS
LOCALE = 'es_MX'
#MARKUP
#MD_EXTENSIONS
#OUTPUT_PATH
#PATH
PAGE_DIR = 'pages'
#PAGE_EXCLUDES
ARTICLE_DIR = 'articles'
#ARTICLE_EXCLUDES
PDF_GENERATOR = False
OUTPUT_SOURCES = False
OUTPUT_SOURCES_EXTENSION = '.text'
RELATIVE_URLS = True
#PLUGINS
SITENAME = u"Grupo de Usuarios de NetBSD en México"
SITEURL = 'http://www.netbsd.mx'
#TEMPLATE_PAGES
STATIC_PATHS = [ "images", ]
TIMEZONE = 'America/Mexico_City'
TYPOGRIFY = False
#DIRECT_TEMPLATES
#PAGINATED_DIRECT_TEMPLATES
SUMMARY_MAX_LENGTH = 58
#EXTA_TEMPLATES_PATHS
#ASCIIDOC_OPTIONS

#ARTICLE_URL
#ARTICLE_SAVE_AS
#ARTICLE_LANG_URL
#ARTICLE_LANG_SAVE_AS
#PAGE_URL
#PAGE_SAVE_AS
#PAGE_LANG_URL
#PAGE_LANG_SAVE_AS
#AUTHOR_URL
#AUTHOR_SAVE_AS
#CATEGORY_URL
#CATEGORY_SAVE_AS
#TAG_URL
#TAG_SAVE_AS

FEED_DOMAIN = SITEURL
FEED_ATOM = 'feeds/feed.atom.xml'
FEED_RSS = 'feeds/feed.rss.xml'
FEED_ALL_ATOM = 'feeds/all.atom.xml'
FEED_ALL_RSS = 'feeds/all.rss.xml'
CATEGORY_FEED_ATOM = 'feeds/%s.atom.xml'
CATEGORY_FEED_RSS = 'feeds/%s.rss.xml'
TAG_FEED_ATOM = 'feeds/%s-tag.atom.xml'
TAG_FEED_RSS = 'feeds/%s-tag.rss.xml'
FEED_MAX_ITEMS = 29

#DEFAULT_ORPHANS
DEFAULT_PAGINATION = 7

#TAG_CLOUD_STEPS
#TAG_CLOUD_MAX_ITEMS

DEFAULT_LANG = 'es'
TRANSLATION_FEED_ATOM = 'feeds/all-%s.atom.xml'
TRANSLATION_FEED_RSS = 'feeds/all-%s.rss.xml'

NEWEST_FIRST_ARCHIVES = True
REVERSE_CATEGORY_ORDER = False

THEME = 'bootlex'
#THEME_STATIC_PATHS
#CSS_FILE

#DISQUS_SITENAME
GITHUB_URL = 'https://github.com/organizations/NetBSD-MX'
#GOOGLE_ANALYTICS
#GOSQUARED_SITENAME
#MENUITEMS
#PIWIK_URL
#PIWIK_SSL_URL
#PIWIK_SITE_ID
LINKS = (
  ('NetBSD', 'http://www.netbsd.org'),
)
SOCIAL = (
  ('twitter', 'http://twitter.com/netbsdmx'),
)
TWITTER_USERNAME = 'netbsdmx'

